---

- name: set time zone
  timezone:
    name: '{{ system_timezone }}'
  tags:
    - timezone

- name: remove unneeded ntp clients
  package:
    name: chrony,ntp
    state: absent

- name: install systemd
  package:
    name: systemd

- name: configure systemd-timesyncd
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  register: timesyncd_config

- name: restart systemd-timesyncd
  service:
    name: systemd-timesyncd
    enabled: yes
    state: restarted
  when: timesyncd_config.changed

- name: enable systemd-timesyncd service and assure it is started
  service:
    name: systemd-timesyncd
    enabled: yes
    state: started
  tags:
    - service
    - service-timesyncd
    - timesyncd-service

...
